### ISSUE TITLE
Delete Monsanto

### ISSUE THREAD

**Issue by alejonext** [kilimchoi/engineering-blogs#265]
I think get to be honest ... I do not think that Monsanto is in the list, since they have little or no ethics.

**Comment by duckspeaker** [comment]
As morally bankrupt as they may be, I feel it still belongs here since it is a decent engineering blog and this repo is simply a list of engineering blogs. In general I'd feel uncomfortable removing a company's engineering blog based on their ethics. It would be like Apple removing all apps with a Confederate flag because people find the flag offensive.

**Comment by alejonext** [comment]
ok...
