### ISSUE TITLE
better to add tags to these links

### ISSUE THREAD

**Issue by djwgit** [kilimchoi/engineering-blogs#555]
the list is nice. it will be more helpful if could tag each link/blog, what are their main topics...
say, somebody want to read blogs about ember-js,  if you have these links tagged, that will easier to find them... thanks

**Comment by djwgit** [comment]
actually, instead of a md file, you could add each link as a github issue, then tag them. easy to sort/find. even could add comment below.

**Comment by kaizensoze** [comment]
Changing the md file to issues might not be such a good idea since it'd make it more difficult to generate an opml file. The single README.md also makes it easier to explore blogs in one place.

Tagging the blogs is probably out of scope for this project. Even if the README.md were changed to issues, creating all the possible different tags to assign and going through the issues would be a royal pain in the ass, but if you're interested, you can always fork it and give it a try!
