### ISSUE TITLE
Feature Request - Categorization

### ISSUE THREAD

**Issue by shubhamagarwal003** [kilimchoi/engineering-blogs#838]
Hi,
This repo seems a great work. A feature request would be to associate categories with these blogs. For example categories like DevOps, Advertising, etc. Would be happy to contribute if you decide to go through this.

**Comment by shubhamagarwal003** [comment]
There is this another repository I came across https://github.com/codelucas/newspaper.  This basically crawls the newspaper and can find keywords. I think a lot from this repository can work for blogs also. Once we have the keywords we can try matching the keywords with right category.
Or other way can be using the above mentioned repository to find the titles of the recent article and estimating categories from that. This may involve some manual work. Would love to know your thoughts.

**Comment by allanbreyes** [comment]
> manual work

A suggestion:

1. Scrape with newspaper and extract keywords
2. Canonicalize them, i.e. downcase
3. **Cross-reference and filter with [Stack Overflow tags](http://data.stackexchange.com/stackoverflow/query/172362/get-all-tags)**
4. Select the top N tags, e.g. N = 3
5. ???
6. Profit!

I explicitly chose tags over categories because the latter probably gets a bit dicey (which one to choose!?). We can work on taxonomy ad nauseum... or we can just tag and call it a day.

**Comment by shubhamagarwal003** [comment]
@allanbreyes This seems like a good idea. We would have to look how newspaper extract keywords, to make sure the quality of keywords extracted are good.

**Comment by allanbreyes** [comment]
> quality of keywords

That's why I suggested cross-referencing with S.O. tags. Those are pretty much guaranteed to be relevant to software.

**Comment by kaizensoze** [comment]
Most of the blogs are mixed and don't really have a specific category so I don't think it'd be worth the effort.
